import { Link } from "react-router-dom";
import { SectionCard } from "../components/SectionCard";

const demoFlow = [
  "Register or login.",
  "Create an organization and project.",
  "Run simulated support-ticket demo data.",
  "Open Dashboard to inspect cost, success rate and cost per successful outcome.",
  "Open Analytics for deeper data quality and outcome distribution.",
  "Generate Recommendations and explain the rule-based evidence.",
  "Export JSON/CSV summary if needed for report screenshots.",
];

const futureScope = [
  "Real OpenAI/Anthropic provider integrations with budget controls",
  "Cloud billing import for AWS, Azure or GCP",
  "Advanced dashboards, alerts and workflow comparison",
  "Role-based permissions and enterprise audit views",
  "ML-based recommendations after enough production data exists",
];

export function DemoGuidePage() {
  return (
    <div className="space-y-6">
      <section className="overflow-hidden rounded-2xl bg-slate-950 px-6 py-8 text-white shadow-xl md:px-10 md:py-10">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand-100">
          Final-year demo guide
        </p>
        <h1 className="mt-3 max-w-4xl text-3xl font-semibold tracking-tight md:text-4xl">
          OutcomeIQ connects AI cost with actual outcome success
        </h1>
        <p className="mt-4 max-w-3xl text-sm leading-6 text-slate-300 md:text-base">
          OutcomeIQ does not only track AI cost. It connects AI cost with actual
          outcome success, helping teams understand whether an AI workflow is
          economically useful after failures, escalations and missing evidence are
          considered.
        </p>
      </section>

      <section className="grid gap-6 xl:grid-cols-2">
        <SectionCard title="1. What is OutcomeIQ?">
          <p className="text-sm leading-6 text-slate-600">
            OutcomeIQ is an outcome-aware AI FinOps platform. It tracks simulated
            AI workflow telemetry, calculates cost and links that spend to business
            outcomes such as succeeded, failed, pending or escalated.
          </p>
        </SectionCard>
        <SectionCard title="2. Problem it solves">
          <p className="text-sm leading-6 text-slate-600">
            Existing tools can show token usage and request cost, but companies
            still struggle to answer: “What did this AI workflow cost per
            successful business outcome?”
          </p>
        </SectionCard>
      </section>

      <SectionCard title="3. Demo flow">
        <ol className="grid gap-3 md:grid-cols-2">
          {demoFlow.map((step, index) => (
            <li className="flex items-start gap-3" key={step}>
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-brand-50 text-xs font-semibold text-brand-700">
                {index + 1}
              </span>
              <span className="pt-1 text-sm text-slate-700">{step}</span>
            </li>
          ))}
        </ol>
        <div className="mt-6 flex flex-wrap gap-3">
          <Link className="primary-button" to="/projects">
            Create project
          </Link>
          <Link className="secondary-button" to="/dashboard">
            Open dashboard
          </Link>
          <Link className="secondary-button" to="/analytics">
            Open analytics
          </Link>
        </div>
      </SectionCard>

      <section className="grid gap-6 xl:grid-cols-2">
        <SectionCard title="4. What demo data represents">
          <p className="text-sm leading-6 text-slate-600">
            The demo uses the support ticket: “My payment failed but money was
            deducted.” It creates two workflow runs with simulated model calls,
            tool calls, costs and outcomes. One run succeeds and one fails, making
            failure waste visible.
          </p>
        </SectionCard>
        <SectionCard title="5. Cost per successful outcome">
          <p className="text-sm leading-6 text-slate-600">
            Cost per successful outcome is calculated by dividing total tracked
            workflow cost by the number of successful verified outcomes. This is
            more business-aware than cost per request alone.
          </p>
        </SectionCard>
      </section>

      <section className="grid gap-6 xl:grid-cols-2">
        <SectionCard title="6. What recommendations mean">
          <p className="text-sm leading-6 text-slate-600">
            Recommendations are deterministic, rule-based observations from backend
            metrics. They are not autonomous actions and they are not generated by
            a real LLM in this MVP.
          </p>
        </SectionCard>
        <SectionCard title="7. What is simulated in MVP">
          <ul className="space-y-2 text-sm leading-6 text-slate-600">
            <li>• Simulated provider/model names</li>
            <li>• Simulated token counts and tool-call costs</li>
            <li>• Simulated customer-support outcomes</li>
            <li>• No real AI-provider keys or billing imports</li>
          </ul>
        </SectionCard>
      </section>

      <SectionCard title="8. Future scope">
        <ul className="grid gap-2 text-sm leading-6 text-slate-600 md:grid-cols-2">
          {futureScope.map((item) => (
            <li key={item}>• {item}</li>
          ))}
        </ul>
      </SectionCard>
    </div>
  );
}
